### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Lxiaoxue** [Just-silent/CCKS_EE#1]
你好，请问这个源代码可以直接运行吗？还是需要添加什么模型

**Comment by Just-silent** [comment]
应该是可以运行的，不知道你遇到什么问题了吗？

**Comment by Lxiaoxue** [comment]
你好，源码中缺少词向量

**Comment by Lxiaoxue** [comment]
基础比较弱，可以提供的详细一点吗？感谢

**Comment by Just-silent** [comment]
哦哦，我没上传，你可以加下我的QQ：1563723284，我发给你，其他问题也可以问我

**Comment by Just-silent** [comment]
> 基础比较弱，可以提供的详细一点吗？感谢

哦哦，我没上传，你可以加下我的QQ：1563723284，我发给你，其他问题也可以问我
