### ISSUE TITLE
项目数据

### ISSUE THREAD

**Issue by cancangit** [Just-silent/CCKS_EE#2]

**Comment by cancangit** [comment]
你好，可以问下项目里面的数据是ccks20年还是19年的？发现项目数据数据量有点对应不上。

**Comment by Just-silent** [comment]
20年的，地址：https://www.biendata.xyz/competition/ccks_2020_2_2/

**Comment by cancangit** [comment]
好的，谢谢您的解答，方便加个微信吗？还有一些问题想咨询下，我的微信号：18840863226.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Just-silent/CCKS_EE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Just-silent/CCKS_EE] 项目数据 (Issue #2)





 
20年的，地址：https://www.biendata.xyz/competition/ccks_2020_2_2/
