### ISSUE TITLE
model

### ISSUE THREAD

**Issue by Mitty-ZH** [Just-silent/CCKS_EE#3]
1、请问model.py里的FLAT是复现的Flat-trasnformers论文吗？
2、最后的结果是单个模型效果还是多模型融合的呢？

**Comment by Just-silent** [comment]
1、model.py里的FLAT是赋值的FLAT关键源代码，这个你可以在论文中找到地址
2、最终的结果是单模型，FLAT需要预训练的词向量，并未利用好该方法，不过FLAT确实是一个词汇增强的有效方法，您可以研究研究
